# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/debris/devel/git/merging-luma/resources/forms/Dialog.ui'
#
# Created: Mon Mar 21 20:19:01 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_serverDialog(object):
    def setupUi(self, serverDialog):
        serverDialog.setObjectName("serverDialog")
        serverDialog.resize(615, 485)
        self.gridLayout_4 = QtGui.QGridLayout(serverDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtGui.QSplitter(serverDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.serverlistGridLayout = QtGui.QGridLayout(self.widget)
        self.serverlistGridLayout.setObjectName("serverlistGridLayout")
        self.serverlistView = QtGui.QListView(self.widget)
        self.serverlistView.setObjectName("serverlistView")
        self.serverlistGridLayout.addWidget(self.serverlistView, 0, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.serverlistGridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.addButton = QtGui.QPushButton(self.widget)
        self.addButton.setObjectName("addButton")
        self.serverlistGridLayout.addWidget(self.addButton, 1, 1, 1, 1)
        self.deleteButton = QtGui.QPushButton(self.widget)
        self.deleteButton.setObjectName("deleteButton")
        self.serverlistGridLayout.addWidget(self.deleteButton, 1, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.networkTab = QtGui.QWidget()
        self.networkTab.setObjectName("networkTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.networkTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vlayout1 = QtGui.QVBoxLayout()
        self.vlayout1.setObjectName("vlayout1")
        self.networkIcon = QtGui.QLabel(self.networkTab)
        self.networkIcon.setMinimumSize(QtCore.QSize(48, 0))
        self.networkIcon.setBaseSize(QtCore.QSize(0, 0))
        self.networkIcon.setText("")
        self.networkIcon.setObjectName("networkIcon")
        self.vlayout1.addWidget(self.networkIcon)
        self.gridLayout_3.addLayout(self.vlayout1, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.networkTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.networkTab)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBox_2)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.pushButton_2)
        self.listWidget = QtGui.QListWidget(self.groupBox_2)
        self.listWidget.setObjectName("listWidget")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.listWidget)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.networkTab, "")
        self.authTab = QtGui.QWidget()
        self.authTab.setObjectName("authTab")
        self.tabWidget.addTab(self.authTab, "")
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.line = QtGui.QFrame(serverDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.bottomHLayout = QtGui.QHBoxLayout()
        self.bottomHLayout.setObjectName("bottomHLayout")
        spacerItem1 = QtGui.QSpacerItem(258, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottomHLayout.addItem(spacerItem1)
        self.okButton = QtGui.QPushButton(serverDialog)
        self.okButton.setObjectName("okButton")
        self.bottomHLayout.addWidget(self.okButton)
        self.applyButton = QtGui.QPushButton(serverDialog)
        self.applyButton.setObjectName("applyButton")
        self.bottomHLayout.addWidget(self.applyButton)
        self.cancelButton = QtGui.QPushButton(serverDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.bottomHLayout.addWidget(self.cancelButton)
        self.gridLayout_4.addLayout(self.bottomHLayout, 3, 0, 1, 1)

        self.retranslateUi(serverDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(serverDialog)

    def retranslateUi(self, serverDialog):
        serverDialog.setWindowTitle(QtGui.QApplication.translate("serverDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("serverDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("serverDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("serverDialog", "Network options", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("serverDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("serverDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("serverDialog", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("serverDialog", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("serverDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("serverDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("serverDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.networkTab), QtGui.QApplication.translate("serverDialog", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.authTab), QtGui.QApplication.translate("serverDialog", "Authentification", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("serverDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("serverDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("serverDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))

