# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/debris/devel/git/luma/resources/forms/ServerDialogDesignNew.ui'
#
# Created: Sun Mar 20 02:34:29 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ServerDialogDesign(object):
    def setupUi(self, ServerDialogDesign):
        ServerDialogDesign.setObjectName("ServerDialogDesign")
        ServerDialogDesign.resize(587, 454)
        self.gridLayout_2 = QtGui.QGridLayout(ServerDialogDesign)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtGui.QSplitter(ServerDialogDesign)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.serverListView = QtGui.QListView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverListView.sizePolicy().hasHeightForWidth())
        self.serverListView.setSizePolicy(sizePolicy)
        self.serverListView.setMinimumSize(QtCore.QSize(182, 0))
        self.serverListView.setObjectName("serverListView")
        self.gridLayout.addWidget(self.serverListView, 0, 0, 1, 3)
        
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        
        self.addButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 1, 1, 1, 1)
        self.deleteButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 1, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.networkTab = QtGui.QWidget()
        self.networkTab.setObjectName("networkTab")
        self.gridLayout_5 = QtGui.QGridLayout(self.networkTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.networkVLayout = QtGui.QVBoxLayout()
        self.networkVLayout.setObjectName("networkVLayout")
        self.networkIcon = QtGui.QLabel(self.networkTab)
        self.networkIcon.setMinimumSize(QtCore.QSize(48, 48))
        self.networkIcon.setText("")
        self.networkIcon.setObjectName("networkIcon")
        self.networkVLayout.addWidget(self.networkIcon)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.networkVLayout.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.networkVLayout, 0, 0, 1, 1)
        self.networkGridLayout = QtGui.QGridLayout()
        self.networkGridLayout.setObjectName("networkGridLayout")
        self.networkOptionsGroup = QtGui.QGroupBox(self.networkTab)
        self.networkOptionsGroup.setObjectName("networkOptionsGroup")
        self.gridLayout_4 = QtGui.QGridLayout(self.networkOptionsGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hostLabel = QtGui.QLabel(self.networkOptionsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostLabel.sizePolicy().hasHeightForWidth())
        self.hostLabel.setSizePolicy(sizePolicy)
        self.hostLabel.setObjectName("hostLabel")
        self.gridLayout_4.addWidget(self.hostLabel, 0, 0, 1, 1)
        self.hostLineEdit = QtGui.QLineEdit(self.networkOptionsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostLineEdit.sizePolicy().hasHeightForWidth())
        self.hostLineEdit.setSizePolicy(sizePolicy)
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.gridLayout_4.addWidget(self.hostLineEdit, 0, 1, 1, 1)
        self.portLabel = QtGui.QLabel(self.networkOptionsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLabel.sizePolicy().hasHeightForWidth())
        self.portLabel.setSizePolicy(sizePolicy)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout_4.addWidget(self.portLabel, 1, 0, 1, 1)
        self.portSpinBox = QtGui.QSpinBox(self.networkOptionsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portSpinBox.sizePolicy().hasHeightForWidth())
        self.portSpinBox.setSizePolicy(sizePolicy)
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setProperty("value", 389)
        self.portSpinBox.setObjectName("portSpinBox")
        self.gridLayout_4.addWidget(self.portSpinBox, 1, 1, 1, 1)
        self.networkGridLayout.addWidget(self.networkOptionsGroup, 0, 0, 1, 1)
        self.LDAPoptionsGoup = QtGui.QGroupBox(self.networkTab)
        self.LDAPoptionsGoup.setObjectName("LDAPoptionsGoup")
        self.gridLayout_3 = QtGui.QGridLayout(self.LDAPoptionsGoup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.aliasBox = QtGui.QCheckBox(self.LDAPoptionsGoup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aliasBox.sizePolicy().hasHeightForWidth())
        self.aliasBox.setSizePolicy(sizePolicy)
        self.aliasBox.setObjectName("aliasBox")
        self.gridLayout_3.addWidget(self.aliasBox, 0, 0, 2, 5)
        self.baseDNLineEdit = QtGui.QLineEdit(self.LDAPoptionsGoup)
        self.baseDNLineEdit.setObjectName("baseDNLineEdit")
        self.gridLayout_3.addWidget(self.baseDNLineEdit, 3, 2, 1, 3)
        self.customBaseDNLabel = QtGui.QLabel(self.LDAPoptionsGoup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customBaseDNLabel.sizePolicy().hasHeightForWidth())
        self.customBaseDNLabel.setSizePolicy(sizePolicy)
        self.customBaseDNLabel.setObjectName("customBaseDNLabel")
        self.gridLayout_3.addWidget(self.customBaseDNLabel, 3, 0, 1, 2)
        self.baseDNListWidget = QtGui.QListWidget(self.LDAPoptionsGoup)
        self.baseDNListWidget.setObjectName("baseDNListWidget")
        self.gridLayout_3.addWidget(self.baseDNListWidget, 5, 0, 1, 5)
        self.baseDNBox = QtGui.QCheckBox(self.LDAPoptionsGoup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseDNBox.sizePolicy().hasHeightForWidth())
        self.baseDNBox.setSizePolicy(sizePolicy)
        self.baseDNBox.setObjectName("baseDNBox")
        self.gridLayout_3.addWidget(self.baseDNBox, 2, 0, 1, 5)
        self.deleteBaseDNButton = QtGui.QPushButton(self.LDAPoptionsGoup)
        self.deleteBaseDNButton.setObjectName("deleteBaseDNButton")
        self.gridLayout_3.addWidget(self.deleteBaseDNButton, 4, 4, 1, 1)
        self.addBaseDNButton = QtGui.QPushButton(self.LDAPoptionsGoup)
        self.addBaseDNButton.setObjectName("addBaseDNButton")
        self.gridLayout_3.addWidget(self.addBaseDNButton, 4, 3, 1, 1)
        self.networkGridLayout.addWidget(self.LDAPoptionsGoup, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.networkGridLayout, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.networkTab, "")
        self.authTab = QtGui.QWidget()
        self.authTab.setObjectName("authTab")
        self.gridLayout_10 = QtGui.QGridLayout(self.authTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.authVLayout = QtGui.QVBoxLayout()
        self.authVLayout.setObjectName("authVLayout")
        self.authIcon = QtGui.QLabel(self.authTab)
        self.authIcon.setMinimumSize(QtCore.QSize(48, 48))
        self.authIcon.setText("")
        self.authIcon.setObjectName("authIcon")
        self.authVLayout.addWidget(self.authIcon)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.authVLayout.addItem(spacerItem3)
        self.gridLayout_10.addLayout(self.authVLayout, 0, 0, 1, 1)
        self.authGridLayout = QtGui.QGridLayout()
        self.authGridLayout.setObjectName("authGridLayout")
        self.bindOptionsGroup = QtGui.QGroupBox(self.authTab)
        self.bindOptionsGroup.setObjectName("bindOptionsGroup")
        self.gridLayout_8 = QtGui.QGridLayout(self.bindOptionsGroup)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.bindAsLabel = QtGui.QLabel(self.bindOptionsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bindAsLabel.sizePolicy().hasHeightForWidth())
        self.bindAsLabel.setSizePolicy(sizePolicy)
        self.bindAsLabel.setObjectName("bindAsLabel")
        self.gridLayout_8.addWidget(self.bindAsLabel, 2, 1, 1, 1)
        self.bindAsLineEdit = QtGui.QLineEdit(self.bindOptionsGroup)
        self.bindAsLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bindAsLineEdit.sizePolicy().hasHeightForWidth())
        self.bindAsLineEdit.setSizePolicy(sizePolicy)
        self.bindAsLineEdit.setObjectName("bindAsLineEdit")
        self.gridLayout_8.addWidget(self.bindAsLineEdit, 2, 3, 1, 1)
        self.passwordLabel = QtGui.QLabel(self.bindOptionsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLabel.sizePolicy().hasHeightForWidth())
        self.passwordLabel.setSizePolicy(sizePolicy)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout_8.addWidget(self.passwordLabel, 3, 1, 1, 1)
        self.anonBindBox = QtGui.QCheckBox(self.bindOptionsGroup)
        self.anonBindBox.setChecked(True)
        self.anonBindBox.setObjectName("anonBindBox")
        self.gridLayout_8.addWidget(self.anonBindBox, 0, 1, 1, 3)
        self.mechanismBox = QtGui.QComboBox(self.bindOptionsGroup)
        self.mechanismBox.setEnabled(False)
        self.mechanismBox.setObjectName("mechanismBox")
        self.mechanismBox.addItem("")
        self.mechanismBox.addItem("")
        self.mechanismBox.addItem("")
        self.mechanismBox.addItem("")
        self.mechanismBox.addItem("")
        self.mechanismBox.addItem("")
        self.mechanismBox.addItem("")
        self.gridLayout_8.addWidget(self.mechanismBox, 1, 3, 1, 1)
        self.mechanismLabel = QtGui.QLabel(self.bindOptionsGroup)
        self.mechanismLabel.setObjectName("mechanismLabel")
        self.gridLayout_8.addWidget(self.mechanismLabel, 1, 1, 1, 1)
        self.passwordLineEdit = QtGui.QLineEdit(self.bindOptionsGroup)
        self.passwordLineEdit.setEnabled(False)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_8.addWidget(self.passwordLineEdit, 3, 3, 1, 1)
        self.authGridLayout.addWidget(self.bindOptionsGroup, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.authGridLayout, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem4, 1, 0, 1, 2)
        self.tabWidget.addTab(self.authTab, "")
        self.securityTab = QtGui.QWidget()
        self.securityTab.setObjectName("securityTab")
        self.gridLayout_13 = QtGui.QGridLayout(self.securityTab)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.securityVLayout = QtGui.QVBoxLayout()
        self.securityVLayout.setObjectName("securityVLayout")
        self.securityIcon = QtGui.QLabel(self.securityTab)
        self.securityIcon.setMinimumSize(QtCore.QSize(48, 48))
        self.securityIcon.setText("")
        self.securityIcon.setObjectName("securityIcon")
        self.securityVLayout.addWidget(self.securityIcon)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.securityVLayout.addItem(spacerItem5)
        self.gridLayout_13.addLayout(self.securityVLayout, 0, 0, 1, 1)
        self.securityGridLayout = QtGui.QGridLayout()
        self.securityGridLayout.setObjectName("securityGridLayout")
        self.securityOptionsGroup = QtGui.QGroupBox(self.securityTab)
        self.securityOptionsGroup.setObjectName("securityOptionsGroup")
        self.gridLayout_11 = QtGui.QGridLayout(self.securityOptionsGroup)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.encryptionBox = QtGui.QComboBox(self.securityOptionsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encryptionBox.sizePolicy().hasHeightForWidth())
        self.encryptionBox.setSizePolicy(sizePolicy)
        self.encryptionBox.setObjectName("encryptionBox")
        self.encryptionBox.addItem("")
        self.encryptionBox.addItem("")
        self.encryptionBox.addItem("")
        self.gridLayout_11.addWidget(self.encryptionBox, 0, 0, 1, 1)
        self.securityGridLayout.addWidget(self.securityOptionsGroup, 0, 0, 1, 1)
        self.ValidateServerCertGroup = QtGui.QGroupBox(self.securityTab)
        self.ValidateServerCertGroup.setObjectName("ValidateServerCertGroup")
        self.gridLayout_12 = QtGui.QGridLayout(self.ValidateServerCertGroup)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.serverCertBox = QtGui.QComboBox(self.ValidateServerCertGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverCertBox.sizePolicy().hasHeightForWidth())
        self.serverCertBox.setSizePolicy(sizePolicy)
        self.serverCertBox.setObjectName("serverCertBox")
        self.serverCertBox.addItem("")
        self.serverCertBox.addItem("")
        self.serverCertBox.addItem("")
        self.serverCertBox.addItem("")
        self.gridLayout_12.addWidget(self.serverCertBox, 0, 0, 1, 2)
        self.securityGridLayout.addWidget(self.ValidateServerCertGroup, 1, 0, 1, 1)
        self.ClientCertGroup = QtGui.QGroupBox(self.securityTab)
        self.ClientCertGroup.setObjectName("ClientCertGroup")
        self.gridLayout_14 = QtGui.QGridLayout(self.ClientCertGroup)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.useClientCertBox = QtGui.QCheckBox(self.ClientCertGroup)
        self.useClientCertBox.setObjectName("useClientCertBox")
        self.gridLayout_14.addWidget(self.useClientCertBox, 0, 0, 1, 2)
        self.certFileLabel = QtGui.QLabel(self.ClientCertGroup)
        self.certFileLabel.setObjectName("certFileLabel")
        self.gridLayout_14.addWidget(self.certFileLabel, 1, 0, 1, 1)
        self.certKeyfileLabel = QtGui.QLabel(self.ClientCertGroup)
        self.certKeyfileLabel.setObjectName("certKeyfileLabel")
        self.gridLayout_14.addWidget(self.certKeyfileLabel, 4, 0, 1, 1)
        self.certFileLineEdit = QtGui.QLineEdit(self.ClientCertGroup)
        self.certFileLineEdit.setEnabled(False)
        self.certFileLineEdit.setObjectName("certFileLineEdit")
        self.gridLayout_14.addWidget(self.certFileLineEdit, 1, 1, 1, 1)
        self.certKeyfileLineEdit = QtGui.QLineEdit(self.ClientCertGroup)
        self.certKeyfileLineEdit.setEnabled(False)
        self.certKeyfileLineEdit.setObjectName("certKeyfileLineEdit")
        self.gridLayout_14.addWidget(self.certKeyfileLineEdit, 4, 1, 1, 1)
        self.certFileButton = QtGui.QToolButton(self.ClientCertGroup)
        self.certFileButton.setEnabled(False)
        self.certFileButton.setObjectName("certFileButton")
        self.gridLayout_14.addWidget(self.certFileButton, 1, 2, 1, 1)
        self.certKeyfileButton = QtGui.QToolButton(self.ClientCertGroup)
        self.certKeyfileButton.setEnabled(False)
        self.certKeyfileButton.setObjectName("certKeyfileButton")
        self.gridLayout_14.addWidget(self.certKeyfileButton, 4, 2, 1, 1)
        self.securityGridLayout.addWidget(self.ClientCertGroup, 2, 0, 1, 1)
        self.gridLayout_13.addLayout(self.securityGridLayout, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem6, 1, 0, 1, 2)
        self.tabWidget.addTab(self.securityTab, "")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.line = QtGui.QFrame(ServerDialogDesign)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.bottomHLayout = QtGui.QHBoxLayout()
        self.bottomHLayout.setObjectName("bottomHLayout")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottomHLayout.addItem(spacerItem7)
        self.okButton = QtGui.QPushButton(ServerDialogDesign)
        self.okButton.setObjectName("okButton")
        self.bottomHLayout.addWidget(self.okButton)
        self.applyButton = QtGui.QPushButton(ServerDialogDesign)
        self.applyButton.setObjectName("applyButton")
        self.bottomHLayout.addWidget(self.applyButton)
        self.cancelButton = QtGui.QPushButton(ServerDialogDesign)
        self.cancelButton.setObjectName("cancelButton")
        self.bottomHLayout.addWidget(self.cancelButton)
        self.gridLayout_2.addLayout(self.bottomHLayout, 2, 0, 1, 1)

        self.retranslateUi(ServerDialogDesign)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.baseDNBox, QtCore.SIGNAL("toggled(bool)"), self.addBaseDNButton.setDisabled)
        QtCore.QObject.connect(self.applyButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.saveServers)
        QtCore.QObject.connect(self.baseDNBox, QtCore.SIGNAL("toggled(bool)"), self.deleteBaseDNButton.setDisabled)
        QtCore.QObject.connect(self.addBaseDNButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.addBaseDN)
        QtCore.QObject.connect(self.addButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.addServer)
        QtCore.QObject.connect(self.baseDNBox, QtCore.SIGNAL("toggled(bool)"), self.baseDNLineEdit.setDisabled)
        QtCore.QObject.connect(self.baseDNBox, QtCore.SIGNAL("toggled(bool)"), self.baseDNListWidget.setDisabled)
        QtCore.QObject.connect(self.baseDNLineEdit, QtCore.SIGNAL("returnPressed()"), ServerDialogDesign.addBaseDN)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.reject)
        QtCore.QObject.connect(self.certFileButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.certFileDialog)
        QtCore.QObject.connect(self.certKeyfileButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.certKeyfileDialog)
        QtCore.QObject.connect(self.deleteBaseDNButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.deleteBaseDN)
        QtCore.QObject.connect(self.deleteButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.deleteServer)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.accept)
        QtCore.QObject.connect(self.useClientCertBox, QtCore.SIGNAL("toggled(bool)"), self.certFileLineEdit.setEnabled)
        QtCore.QObject.connect(self.useClientCertBox, QtCore.SIGNAL("toggled(bool)"), self.certKeyfileLineEdit.setEnabled)
        QtCore.QObject.connect(self.useClientCertBox, QtCore.SIGNAL("toggled(bool)"), self.certFileButton.setEnabled)
        QtCore.QObject.connect(self.useClientCertBox, QtCore.SIGNAL("toggled(bool)"), self.certKeyfileButton.setEnabled)
        QtCore.QObject.connect(self.anonBindBox, QtCore.SIGNAL("toggled(bool)"), self.mechanismBox.setDisabled)
        QtCore.QObject.connect(self.anonBindBox, QtCore.SIGNAL("toggled(bool)"), self.bindAsLineEdit.setDisabled)
        QtCore.QObject.connect(self.anonBindBox, QtCore.SIGNAL("toggled(bool)"), self.passwordLineEdit.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(ServerDialogDesign)

    def retranslateUi(self, ServerDialogDesign):
        ServerDialogDesign.setWindowTitle(QtGui.QApplication.translate("ServerDialogDesign", "Manage Serverlist", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.networkOptionsGroup.setTitle(QtGui.QApplication.translate("ServerDialogDesign", "Network options", None, QtGui.QApplication.UnicodeUTF8))
        self.hostLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.portLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.LDAPoptionsGoup.setTitle(QtGui.QApplication.translate("ServerDialogDesign", "LDAP options", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasBox.setText(QtGui.QApplication.translate("ServerDialogDesign", "Follow aliases", None, QtGui.QApplication.UnicodeUTF8))
        self.customBaseDNLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "Custom:", None, QtGui.QApplication.UnicodeUTF8))
        self.baseDNBox.setText(QtGui.QApplication.translate("ServerDialogDesign", "Use Base DN provided by the server", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteBaseDNButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.addBaseDNButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.networkTab), QtGui.QApplication.translate("ServerDialogDesign", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.bindOptionsGroup.setTitle(QtGui.QApplication.translate("ServerDialogDesign", "Bind options", None, QtGui.QApplication.UnicodeUTF8))
        self.bindAsLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "Bind as:", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.anonBindBox.setText(QtGui.QApplication.translate("ServerDialogDesign", "Anonymous bind", None, QtGui.QApplication.UnicodeUTF8))
        self.mechanismBox.setItemText(0, QtGui.QApplication.translate("ServerDialogDesign", "Simple", None, QtGui.QApplication.UnicodeUTF8))
        self.mechanismBox.setItemText(1, QtGui.QApplication.translate("ServerDialogDesign", "SASL CRAM-MD5", None, QtGui.QApplication.UnicodeUTF8))
        self.mechanismBox.setItemText(2, QtGui.QApplication.translate("ServerDialogDesign", "SASL DIGEST-MD5", None, QtGui.QApplication.UnicodeUTF8))
        self.mechanismBox.setItemText(3, QtGui.QApplication.translate("ServerDialogDesign", "SASL EXTERNAL", None, QtGui.QApplication.UnicodeUTF8))
        self.mechanismBox.setItemText(4, QtGui.QApplication.translate("ServerDialogDesign", "SASL GSSAPI", None, QtGui.QApplication.UnicodeUTF8))
        self.mechanismBox.setItemText(5, QtGui.QApplication.translate("ServerDialogDesign", "SASL Login", None, QtGui.QApplication.UnicodeUTF8))
        self.mechanismBox.setItemText(6, QtGui.QApplication.translate("ServerDialogDesign", "SASL Plain", None, QtGui.QApplication.UnicodeUTF8))
        self.mechanismLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "Mechanism:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.authTab), QtGui.QApplication.translate("ServerDialogDesign", "Authentification", None, QtGui.QApplication.UnicodeUTF8))
        self.securityOptionsGroup.setTitle(QtGui.QApplication.translate("ServerDialogDesign", "Security options", None, QtGui.QApplication.UnicodeUTF8))
        self.encryptionBox.setItemText(0, QtGui.QApplication.translate("ServerDialogDesign", "Unencrypted connection", None, QtGui.QApplication.UnicodeUTF8))
        self.encryptionBox.setItemText(1, QtGui.QApplication.translate("ServerDialogDesign", "Transport Layer Security (TLS)", None, QtGui.QApplication.UnicodeUTF8))
        self.encryptionBox.setItemText(2, QtGui.QApplication.translate("ServerDialogDesign", "Secure Socket Layer (SSL)", None, QtGui.QApplication.UnicodeUTF8))
        self.ValidateServerCertGroup.setTitle(QtGui.QApplication.translate("ServerDialogDesign", "Validate server certificate", None, QtGui.QApplication.UnicodeUTF8))
        self.serverCertBox.setItemText(0, QtGui.QApplication.translate("ServerDialogDesign", "Never", None, QtGui.QApplication.UnicodeUTF8))
        self.serverCertBox.setItemText(1, QtGui.QApplication.translate("ServerDialogDesign", "Allow", None, QtGui.QApplication.UnicodeUTF8))
        self.serverCertBox.setItemText(2, QtGui.QApplication.translate("ServerDialogDesign", "Try", None, QtGui.QApplication.UnicodeUTF8))
        self.serverCertBox.setItemText(3, QtGui.QApplication.translate("ServerDialogDesign", "Demand", None, QtGui.QApplication.UnicodeUTF8))
        self.ClientCertGroup.setTitle(QtGui.QApplication.translate("ServerDialogDesign", "Client certificate options", None, QtGui.QApplication.UnicodeUTF8))
        self.useClientCertBox.setText(QtGui.QApplication.translate("ServerDialogDesign", "Use client certificates", None, QtGui.QApplication.UnicodeUTF8))
        self.certFileLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "Certificate file:", None, QtGui.QApplication.UnicodeUTF8))
        self.certKeyfileLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "Certificate keyfile:", None, QtGui.QApplication.UnicodeUTF8))
        self.certFileButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.certKeyfileButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.securityTab), QtGui.QApplication.translate("ServerDialogDesign", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "&Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))

