# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Skole\it2901\resources\forms\plugins\template\AddAttributeDialogDesign.ui'
#
# Created: Fri Mar 18 16:09:46 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AddAttributeDialog(object):
    def setupUi(self, AddAttributeDialog):
        AddAttributeDialog.setObjectName(_fromUtf8("AddAttributeDialog"))
        AddAttributeDialog.resize(500, 300)
        self.gridLayout_2 = QtGui.QGridLayout(AddAttributeDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelMain = QtGui.QLabel(AddAttributeDialog)
        self.labelMain.setWordWrap(True)
        self.labelMain.setObjectName(_fromUtf8("labelMain"))
        self.gridLayout_2.addWidget(self.labelMain, 0, 1, 1, 3)
        self.pushButtonCancel = QtGui.QPushButton(AddAttributeDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCancel.sizePolicy().hasHeightForWidth())
        self.pushButtonCancel.setSizePolicy(sizePolicy)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.gridLayout_2.addWidget(self.pushButtonCancel, 4, 3, 1, 1)
        self.pushButtonOk = QtGui.QPushButton(AddAttributeDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOk.sizePolicy().hasHeightForWidth())
        self.pushButtonOk.setSizePolicy(sizePolicy)
        self.pushButtonOk.setObjectName(_fromUtf8("pushButtonOk"))
        self.gridLayout_2.addWidget(self.pushButtonOk, 4, 2, 1, 1)
        self.line = QtGui.QFrame(AddAttributeDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 4)
        self.splitter = QtGui.QSplitter(AddAttributeDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.listView = QtGui.QListView(self.splitter)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelAttributeInformation = QtGui.QLabel(self.layoutWidget)
        self.labelAttributeInformation.setMinimumSize(QtCore.QSize(0, 20))
        self.labelAttributeInformation.setObjectName(_fromUtf8("labelAttributeInformation"))
        self.gridLayout.addWidget(self.labelAttributeInformation, 0, 0, 1, 2)
        self.labelMust = QtGui.QLabel(self.layoutWidget)
        self.labelMust.setMinimumSize(QtCore.QSize(0, 20))
        self.labelMust.setObjectName(_fromUtf8("labelMust"))
        self.gridLayout.addWidget(self.labelMust, 1, 0, 1, 1)
        self.labelMustIcon = QtGui.QLabel(self.layoutWidget)
        self.labelMustIcon.setText(_fromUtf8(""))
        self.labelMustIcon.setObjectName(_fromUtf8("labelMustIcon"))
        self.gridLayout.addWidget(self.labelMustIcon, 1, 1, 1, 1)
        self.labelSingle = QtGui.QLabel(self.layoutWidget)
        self.labelSingle.setMinimumSize(QtCore.QSize(0, 20))
        self.labelSingle.setObjectName(_fromUtf8("labelSingle"))
        self.gridLayout.addWidget(self.labelSingle, 2, 0, 1, 1)
        self.labelSingleIcon = QtGui.QLabel(self.layoutWidget)
        self.labelSingleIcon.setText(_fromUtf8(""))
        self.labelSingleIcon.setObjectName(_fromUtf8("labelSingleIcon"))
        self.gridLayout.addWidget(self.labelSingleIcon, 2, 1, 1, 1)
        self.labelBinary = QtGui.QLabel(self.layoutWidget)
        self.labelBinary.setMinimumSize(QtCore.QSize(0, 20))
        self.labelBinary.setObjectName(_fromUtf8("labelBinary"))
        self.gridLayout.addWidget(self.labelBinary, 3, 0, 1, 1)
        self.labelBinaryIcon = QtGui.QLabel(self.layoutWidget)
        self.labelBinaryIcon.setText(_fromUtf8(""))
        self.labelBinaryIcon.setObjectName(_fromUtf8("labelBinaryIcon"))
        self.gridLayout.addWidget(self.labelBinaryIcon, 3, 1, 1, 1)
        self.labelDefaultValue = QtGui.QLabel(self.layoutWidget)
        self.labelDefaultValue.setObjectName(_fromUtf8("labelDefaultValue"))
        self.gridLayout.addWidget(self.labelDefaultValue, 4, 0, 1, 1)
        self.lineEditDefaultValue = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditDefaultValue.setObjectName(_fromUtf8("lineEditDefaultValue"))
        self.gridLayout.addWidget(self.lineEditDefaultValue, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 2)
        self.gridLayout_2.addWidget(self.splitter, 2, 0, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 2)
        self.line_2 = QtGui.QFrame(AddAttributeDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 4)
        self.labelMainIcon = QtGui.QLabel(AddAttributeDialog)
        self.labelMainIcon.setText(_fromUtf8(""))
        self.labelMainIcon.setObjectName(_fromUtf8("labelMainIcon"))
        self.gridLayout_2.addWidget(self.labelMainIcon, 0, 0, 1, 1)

        self.retranslateUi(AddAttributeDialog)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), AddAttributeDialog.reject)
        QtCore.QObject.connect(self.pushButtonOk, QtCore.SIGNAL(_fromUtf8("clicked()")), AddAttributeDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(AddAttributeDialog)

    def retranslateUi(self, AddAttributeDialog):
        AddAttributeDialog.setWindowTitle(QtGui.QApplication.translate("AddAttributeDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain.setText(QtGui.QApplication.translate("AddAttributeDialog", "Please select the attributes you want to add.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("AddAttributeDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setText(QtGui.QApplication.translate("AddAttributeDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAttributeInformation.setText(QtGui.QApplication.translate("AddAttributeDialog", "Attribute information", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMust.setText(QtGui.QApplication.translate("AddAttributeDialog", "Must:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSingle.setText(QtGui.QApplication.translate("AddAttributeDialog", "Single:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBinary.setText(QtGui.QApplication.translate("AddAttributeDialog", "Binary:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDefaultValue.setText(QtGui.QApplication.translate("AddAttributeDialog", "Default value:", None, QtGui.QApplication.UnicodeUTF8))

