# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base\gui\BaseSelectorDesign.ui'
#
# Created: Wed Feb 09 18:26:24 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BaseSelectorDesign(object):
    def baseDNEditself, BaseSelectorDesign):
        BaseSelectorDesign.setObjectName(_fromUtf8("BaseSelectorDesign"))
        BaseSelectorDesign.resize(551, 456)
        self.vboxlayout = QtGui.QVBoxLayout(BaseSelectorDesign)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.baseLabel = QtGui.QLabel(BaseSelectorDesign)
        self.baseLabel.setAlignment(QtCore.Qt.AlignVCenter)
        self.baseLabel.setWordWrap(True)
        self.baseLabel.setObjectName(_fromUtf8("baseLabel"))
        self.gridlayout.addWidget(self.baseLabel, 0, 1, 1, 1)
        self.pixmapLabel1 = QtGui.QLabel(BaseSelectorDesign)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmapLabel1.sizePolicy().hasHeightForWidth())
        self.pixmapLabel1.setSizePolicy(sizePolicy)
        self.pixmapLabel1.setScaledContents(True)
        self.pixmapLabel1.setWordWrap(False)
        self.pixmapLabel1.setObjectName(_fromUtf8("pixmapLabel1"))
        self.gridlayout.addWidget(self.pixmapLabel1, 0, 0, 1, 1)
        self.line2 = QtGui.QFrame(BaseSelectorDesign)
        self.line2.setFrameShape(QtGui.QFrame.HLine)
        self.line2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line2.setObjectName(_fromUtf8("line2"))
        self.gridlayout.addWidget(self.line2, 1, 0, 1, 2)
        self.vboxlayout.addLayout(self.gridlayout)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        spacerItem = QtGui.QSpacerItem(21, 150, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem, 3, 2, 1, 1)
        self.textLabel2 = QtGui.QLabel(BaseSelectorDesign)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName(_fromUtf8("textLabel2"))
        self.gridlayout1.addWidget(self.textLabel2, 0, 0, 1, 1)
        self.deleteButton = QtGui.QPushButton(BaseSelectorDesign)
        self.deleteButton.setAutoDefault(False)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.gridlayout1.addWidget(self.deleteButton, 1, 2, 1, 1)
        self.baseView = QtGui.QListWidget(BaseSelectorDesign)
        self.baseView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.baseView.setObjectName(_fromUtf8("baseView"))
        self.gridlayout1.addWidget(self.baseView, 1, 0, 3, 2)
        self.baseDNEdit = QtGui.QLineEdit(BaseSelectorDesign)
        self.baseDNEdit.setObjectName(_fromUtf8("baseDNEdit"))
        self.gridlayout1.addWidget(self.baseDNEdit, 0, 1, 1, 1)
        self.addButton = QtGui.QPushButton(BaseSelectorDesign)
        self.addButton.setAutoDefault(False)
        self.addButton.setDefault(False)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridlayout1.addWidget(self.addButton, 0, 2, 1, 1)
        self.updateButton = QtGui.QPushButton(BaseSelectorDesign)
        self.updateButton.setAutoDefault(False)
        self.updateButton.setObjectName(_fromUtf8("updateButton"))
        self.gridlayout1.addWidget(self.updateButton, 2, 2, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout1)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.line3 = QtGui.QFrame(BaseSelectorDesign)
        self.line3.setFrameShape(QtGui.QFrame.HLine)
        self.line3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line3.setObjectName(_fromUtf8("line3"))
        self.gridlayout2.addWidget(self.line3, 0, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(391, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout2.addItem(spacerItem1, 1, 0, 1, 1)
        self.cancelButton = QtGui.QPushButton(BaseSelectorDesign)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setDefault(False)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridlayout2.addWidget(self.cancelButton, 1, 2, 1, 1)
        self.okButton = QtGui.QPushButton(BaseSelectorDesign)
        self.okButton.setAutoDefault(False)
        self.okButton.setDefault(False)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.gridlayout2.addWidget(self.okButton, 1, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout2)

        self.retranslateUi(BaseSelectorDesign)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BaseSelectorDesign.accept)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BaseSelectorDesign.reject)
        QtCore.QObject.connect(self.addButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BaseSelectorDesign.addBase)
        QtCore.QObject.connect(self.deleteButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BaseSelectorDesign.deleteBase)
        QtCore.QObject.connect(self.updateButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BaseSelectorDesign.addServerBase)
        QtCore.QObject.connect(self.baseDNEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), BaseSelectorDesign.addBase)
        QtCore.QMetaObject.connectSlotsByName(BaseSelectorDesign)
        BaseSelectorDesign.setTabOrder(self.baseDNEdit, self.addButton)
        BaseSelectorDesign.setTabOrder(self.addButton, self.baseView)
        BaseSelectorDesign.setTabOrder(self.baseView, self.deleteButton)
        BaseSelectorDesign.setTabOrder(self.deleteButton, self.updateButton)
        BaseSelectorDesign.setTabOrder(self.updateButton, self.okButton)
        BaseSelectorDesign.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, BaseSelectorDesign):
        BaseSelectorDesign.setWindowTitle(QtGui.QApplication.translate("BaseSelectorDesign", "Select Base DNs", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLabel.setText(QtGui.QApplication.translate("BaseSelectorDesign", "Manage the base distinguished names you want to use with the server", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("BaseSelectorDesign", "Custom:", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("BaseSelectorDesign", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setShortcut(QtGui.QApplication.translate("BaseSelectorDesign", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("BaseSelectorDesign", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setShortcut(QtGui.QApplication.translate("BaseSelectorDesign", "Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("BaseSelectorDesign", "&Update from server", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setShortcut(QtGui.QApplication.translate("BaseSelectorDesign", "Alt+U", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("BaseSelectorDesign", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setShortcut(QtGui.QApplication.translate("BaseSelectorDesign", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("BaseSelectorDesign", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("BaseSelectorDesign", "Alt+O", None, QtGui.QApplication.UnicodeUTF8))

