.TH LUMA(1)  
.SH NAME
\fBluma \fP- LDAP browser, utility and more.
\fB
.SH SYNOPSIS
.nf
.fam C
\fBluma\fP
.fam T
.fi
.SH DESCRIPTION
\fBluma\fP is a graphical utility for accessing and managin data stored on 
LDAP servers. It is written in Python, using PyQT and python-ldap.
Plugin-support is included and useful widgets with LDAP-functionality
for easy creation of plugins are delivered.
.PP
Currently Luma supports: 
english, german, portuguese, french, russion, swedish, norwegian
.PP
The following plugins are available:
.IP \(bu 3
Browser
.IP \(bu 3
Search
.IP \(bu 3
Addressbook
.IP \(bu 3
Schema browser
.IP \(bu 3
Template
.IP \(bu 3
Massive User Creation
.IP \(bu 3
Admin Utilities
.PP
For further documentation, please go to http://luma.sf.net and
click on 'Documentation'
.PP
Yours truly
.PP
Luma Team.
