# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWinDesign.ui'
#
# Created: Tue Feb  1 16:35:58 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWinDesign(object):
    def setupUi(self, MainWinDesign):
        MainWinDesign.setObjectName("MainWinDesign")
        MainWinDesign.resize(479, 321)
        self.widget = QtGui.QWidget(MainWinDesign)
        self.widget.setObjectName("widget")
        self.gridlayout = QtGui.QGridLayout(self.widget)
        self.gridlayout.setObjectName("gridlayout")
        self.taskStack = QtGui.QStackedWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskStack.sizePolicy().hasHeightForWidth())
        self.taskStack.setSizePolicy(sizePolicy)
        self.taskStack.setObjectName("taskStack")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.taskStack.addWidget(self.page)
        self.gridlayout.addWidget(self.taskStack, 0, 0, 1, 1)
        MainWinDesign.setCentralWidget(self.widget)
        self.menubar = QtGui.QMenuBar(MainWinDesign)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 479, 25))
        self.menubar.setObjectName("menubar")
        self.menuProgram = QtGui.QMenu(self.menubar)
        self.menuProgram.setObjectName("menuProgram")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWinDesign.setMenuBar(self.menubar)
        self.actionAbout = QtGui.QAction(MainWinDesign)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../tags/Luma-3.0a/luma/lib/luma/base/gui/image0"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionEditServerList = QtGui.QAction(MainWinDesign)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../tags/Luma-3.0a/luma/lib/luma/base/gui/image1"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditServerList.setIcon(icon1)
        self.actionEditServerList.setObjectName("actionEditServerList")
        self.actionExit = QtGui.QAction(MainWinDesign)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../tags/Luma-3.0a/luma/lib/luma/base/gui/image2"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionConfigurePlugins = QtGui.QAction(MainWinDesign)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../tags/Luma-3.0a/luma/lib/luma/base/gui/image3"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigurePlugins.setIcon(icon3)
        self.actionConfigurePlugins.setShortcut("")
        self.actionConfigurePlugins.setObjectName("actionConfigurePlugins")
        self.actionReloadPlugins = QtGui.QAction(MainWinDesign)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../tags/Luma-3.0a/luma/lib/luma/base/gui/image4"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReloadPlugins.setIcon(icon4)
        self.actionReloadPlugins.setShortcut("")
        self.actionReloadPlugins.setObjectName("actionReloadPlugins")
        self.actionSelectLanguage = QtGui.QAction(MainWinDesign)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../tags/Luma-3.0a/luma/lib/luma/base/gui/image5"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectLanguage.setIcon(icon5)
        self.actionSelectLanguage.setShortcut("")
        self.actionSelectLanguage.setObjectName("actionSelectLanguage")
        self.actionShowLogger = QtGui.QAction(MainWinDesign)
        self.actionShowLogger.setCheckable(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../../tags/Luma-3.0a/luma/lib/luma/base/gui/image6"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowLogger.setIcon(icon6)
        self.actionShowLogger.setShortcut("")
        self.actionShowLogger.setObjectName("actionShowLogger")
        self.actionK_l = QtGui.QAction(MainWinDesign)
        self.actionK_l.setObjectName("actionK_l")
        self.actionPlay = QtGui.QAction(MainWinDesign)
        self.actionPlay.setObjectName("actionPlay")
        self.menuProgram.addAction(self.actionShowLogger)
        self.menuProgram.addAction(self.actionReloadPlugins)
        self.menuProgram.addSeparator()
        self.menuProgram.addAction(self.actionExit)
        self.menuProgram.addSeparator()
        self.menuSettings.addAction(self.actionEditServerList)
        self.menuSettings.addAction(self.actionConfigurePlugins)
        self.menuSettings.addAction(self.actionSelectLanguage)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuProgram.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWinDesign)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL("activated()"), MainWinDesign.showAboutLuma)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWinDesign.quitApplication)
        QtCore.QObject.connect(self.actionEditServerList, QtCore.SIGNAL("activated()"), MainWinDesign.showServerEditor)
        QtCore.QObject.connect(self.actionConfigurePlugins, QtCore.SIGNAL("activated()"), MainWinDesign.configurePlugins)
        QtCore.QObject.connect(self.actionReloadPlugins, QtCore.SIGNAL("activated()"), MainWinDesign.reloadPlugins)
        QtCore.QObject.connect(self.actionSelectLanguage, QtCore.SIGNAL("activated()"), MainWinDesign.showLanguageDialog)
        QtCore.QObject.connect(self.actionShowLogger, QtCore.SIGNAL("activated()"), MainWinDesign.showLoggerWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWinDesign)

    def retranslateUi(self, MainWinDesign):
        MainWinDesign.setWindowTitle(QtGui.QApplication.translate("MainWinDesign", "Luma", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProgram.setTitle(QtGui.QApplication.translate("MainWinDesign", "&Program", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWinDesign", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWinDesign", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWinDesign", "About Luma...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setIconText(QtGui.QApplication.translate("MainWinDesign", "About Luma...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setProperty("name", QtGui.QApplication.translate("MainWinDesign", "about", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditServerList.setText(QtGui.QApplication.translate("MainWinDesign", "Edit Server List...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditServerList.setIconText(QtGui.QApplication.translate("MainWinDesign", "Edit Server List...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditServerList.setShortcut(QtGui.QApplication.translate("MainWinDesign", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditServerList.setProperty("name", QtGui.QApplication.translate("MainWinDesign", "editServerList", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWinDesign", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setIconText(QtGui.QApplication.translate("MainWinDesign", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWinDesign", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setProperty("name", QtGui.QApplication.translate("MainWinDesign", "exitItem", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigurePlugins.setText(QtGui.QApplication.translate("MainWinDesign", "Configure Plugins...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigurePlugins.setIconText(QtGui.QApplication.translate("MainWinDesign", "Configure Plugins...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigurePlugins.setProperty("name", QtGui.QApplication.translate("MainWinDesign", "menuConfigurePlugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadPlugins.setText(QtGui.QApplication.translate("MainWinDesign", "Reload Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadPlugins.setIconText(QtGui.QApplication.translate("MainWinDesign", "Reload Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadPlugins.setProperty("name", QtGui.QApplication.translate("MainWinDesign", "reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectLanguage.setText(QtGui.QApplication.translate("MainWinDesign", "Language...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectLanguage.setIconText(QtGui.QApplication.translate("MainWinDesign", "Language...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectLanguage.setProperty("name", QtGui.QApplication.translate("MainWinDesign", "selectLanguage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowLogger.setText(QtGui.QApplication.translate("MainWinDesign", "Show Logger", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowLogger.setIconText(QtGui.QApplication.translate("MainWinDesign", "Show logger", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowLogger.setProperty("name", QtGui.QApplication.translate("MainWinDesign", "showLogger", None, QtGui.QApplication.UnicodeUTF8))
        self.actionK_l.setText(QtGui.QApplication.translate("MainWinDesign", "køl", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWinDesign", "Play", None, QtGui.QApplication.UnicodeUTF8))

