# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServerDialogDesign.ui'
#
# Created: Tue Feb  8 18:42:33 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ServerDialogDesign(object):
    def setupUi(self, ServerDialogDesign):
        ServerDialogDesign.setObjectName("ServerDialogDesign")
        ServerDialogDesign.resize(754, 504)
        self.vboxlayout = QtGui.QVBoxLayout(ServerDialogDesign)
        self.vboxlayout.setObjectName("vboxlayout")
        self.splitter2 = QtGui.QSplitter(ServerDialogDesign)
        self.splitter2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter2.setObjectName("splitter2")
        self.layout3 = QtGui.QWidget(self.splitter2)
        self.layout3.setObjectName("layout3")
        self.gridlayout = QtGui.QGridLayout(self.layout3)
        self.gridlayout.setMargin(0)
        self.gridlayout.setObjectName("gridlayout")
        spacerItem = QtGui.QSpacerItem(48, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 1, 1, 1, 1)
        self.addButton = QtGui.QPushButton(self.layout3)
        self.addButton.setObjectName("addButton")
        self.gridlayout.addWidget(self.addButton, 1, 2, 1, 1)
        self.deleteButton = QtGui.QPushButton(self.layout3)
        self.deleteButton.setObjectName("deleteButton")
        self.gridlayout.addWidget(self.deleteButton, 1, 3, 1, 1)
        self.listView = QtGui.QListView(self.layout3)
        self.listView.setObjectName("listView")
        self.gridlayout.addWidget(self.listView, 0, 1, 1, 3)
        self.serverWidget = QtGui.QTabWidget(self.splitter2)
        self.serverWidget.setObjectName("serverWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridlayout1 = QtGui.QGridLayout(self.tab)
        self.gridlayout1.setObjectName("gridlayout1")
        spacerItem1 = QtGui.QSpacerItem(21, 263, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 2, 0, 7, 1)
        self.networkLabel = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.networkLabel.sizePolicy().hasHeightForWidth())
        self.networkLabel.setSizePolicy(sizePolicy)
        self.networkLabel.setMinimumSize(QtCore.QSize(48, 48))
        self.networkLabel.setWordWrap(False)
        self.networkLabel.setObjectName("networkLabel")
        self.gridlayout1.addWidget(self.networkLabel, 0, 0, 2, 1)
        self.textLabel1_2 = QtGui.QLabel(self.tab)
        self.textLabel1_2.setAlignment(QtCore.Qt.AlignVCenter)
        self.textLabel1_2.setWordWrap(True)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.gridlayout1.addWidget(self.textLabel1_2, 0, 1, 1, 6)
        self.portSpinBox = QtGui.QSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portSpinBox.sizePolicy().hasHeightForWidth())
        self.portSpinBox.setSizePolicy(sizePolicy)
        self.portSpinBox.setMinimum(1)
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setProperty("value", 389)
        self.portSpinBox.setObjectName("portSpinBox")
        self.gridlayout1.addWidget(self.portSpinBox, 3, 3, 1, 4)
        self.hostLineEdit = QtGui.QLineEdit(self.tab)
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.gridlayout1.addWidget(self.hostLineEdit, 1, 3, 2, 4)
        self.textLabel9 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel9.sizePolicy().hasHeightForWidth())
        self.textLabel9.setSizePolicy(sizePolicy)
        self.textLabel9.setWordWrap(False)
        self.textLabel9.setObjectName("textLabel9")
        self.gridlayout1.addWidget(self.textLabel9, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(12, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 1, 1, 1, 1)
        self.textLabel8 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel8.sizePolicy().hasHeightForWidth())
        self.textLabel8.setSizePolicy(sizePolicy)
        self.textLabel8.setWordWrap(False)
        self.textLabel8.setObjectName("textLabel8")
        self.gridlayout1.addWidget(self.textLabel8, 1, 2, 2, 1)
        self.aliasBox = QtGui.QCheckBox(self.tab)
        self.aliasBox.setObjectName("aliasBox")
        self.gridlayout1.addWidget(self.aliasBox, 6, 2, 1, 5)
        self.baseBox = QtGui.QCheckBox(self.tab)
        self.baseBox.setObjectName("baseBox")
        self.gridlayout1.addWidget(self.baseBox, 7, 2, 1, 5)
        self.textLabel1 = QtGui.QLabel(self.tab)
        self.textLabel1.setAlignment(QtCore.Qt.AlignVCenter)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout1.addWidget(self.textLabel1, 5, 1, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem3, 6, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(124, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem4, 9, 2, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(20, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridlayout1.addItem(spacerItem5, 4, 2, 1, 1)
        self.removeBaseDN = QtGui.QPushButton(self.tab)
        self.removeBaseDN.setEnabled(True)
        self.removeBaseDN.setObjectName("removeBaseDN")
        self.gridlayout1.addWidget(self.removeBaseDN, 9, 6, 1, 1)
        self.addBaseDN = QtGui.QPushButton(self.tab)
        self.addBaseDN.setEnabled(True)
        self.addBaseDN.setObjectName("addBaseDN")
        self.gridlayout1.addWidget(self.addBaseDN, 9, 5, 1, 1)
        self.baseDNView = QtGui.QListView(self.tab)
        self.baseDNView.setSelectionRectVisible(True)
        self.baseDNView.setObjectName("baseDNView")
        self.gridlayout1.addWidget(self.baseDNView, 8, 5, 1, 2)
        self.serverWidget.addTab(self.tab, "")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem6 = QtGui.QSpacerItem(114, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 2, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textLabel1_4 = QtGui.QLabel(self.tab1)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridLayout.addWidget(self.textLabel1_4, 0, 0, 1, 3)
        spacerItem7 = QtGui.QSpacerItem(13, 18, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        self.bindAnonBox = QtGui.QCheckBox(self.tab1)
        self.bindAnonBox.setObjectName("bindAnonBox")
        self.gridLayout.addWidget(self.bindAnonBox, 1, 1, 1, 2)
        self.textLabel4 = QtGui.QLabel(self.tab1)
        self.textLabel4.setAlignment(QtCore.Qt.AlignVCenter)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout.addWidget(self.textLabel4, 2, 1, 1, 1)
        self.methodBox = QtGui.QComboBox(self.tab1)
        self.methodBox.setObjectName("methodBox")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.gridLayout.addWidget(self.methodBox, 2, 2, 1, 1)
        self.textLabel10 = QtGui.QLabel(self.tab1)
        self.textLabel10.setAlignment(QtCore.Qt.AlignVCenter)
        self.textLabel10.setWordWrap(True)
        self.textLabel10.setObjectName("textLabel10")
        self.gridLayout.addWidget(self.textLabel10, 3, 1, 1, 1)
        self.bindLineEdit = QtGui.QLineEdit(self.tab1)
        self.bindLineEdit.setObjectName("bindLineEdit")
        self.gridLayout.addWidget(self.bindLineEdit, 3, 2, 1, 1)
        self.textLabel12 = QtGui.QLabel(self.tab1)
        self.textLabel12.setAlignment(QtCore.Qt.AlignVCenter)
        self.textLabel12.setWordWrap(False)
        self.textLabel12.setObjectName("textLabel12")
        self.gridLayout.addWidget(self.textLabel12, 4, 1, 1, 1)
        self.passwordLineEdit = QtGui.QLineEdit(self.tab1)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 4, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 2, 1)
        self.authLabel = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authLabel.sizePolicy().hasHeightForWidth())
        self.authLabel.setSizePolicy(sizePolicy)
        self.authLabel.setMinimumSize(QtCore.QSize(48, 48))
        self.authLabel.setWordWrap(False)
        self.authLabel.setObjectName("authLabel")
        self.gridLayout_3.addWidget(self.authLabel, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(45, 445, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 1, 0, 2, 1)
        self.serverWidget.addTab(self.tab1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.securityLabel = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.securityLabel.sizePolicy().hasHeightForWidth())
        self.securityLabel.setSizePolicy(sizePolicy)
        self.securityLabel.setMinimumSize(QtCore.QSize(48, 48))
        self.securityLabel.setWordWrap(False)
        self.securityLabel.setObjectName("securityLabel")
        self.gridLayout_4.addWidget(self.securityLabel, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel1_10 = QtGui.QLabel(self.tab_2)
        self.textLabel1_10.setWordWrap(False)
        self.textLabel1_10.setObjectName("textLabel1_10")
        self.gridLayout_2.addWidget(self.textLabel1_10, 0, 0, 1, 2)
        self.encryptionBox = QtGui.QComboBox(self.tab_2)
        self.encryptionBox.setObjectName("encryptionBox")
        self.encryptionBox.addItem("")
        self.encryptionBox.addItem("")
        self.encryptionBox.addItem("")
        self.gridLayout_2.addWidget(self.encryptionBox, 1, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(16, 16, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 2)
        spacerItem10 = QtGui.QSpacerItem(45, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 1, 0, 5, 1)
        spacerItem11 = QtGui.QSpacerItem(21, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem11, 1, 1, 1, 1)
        self._7 = QtGui.QGridLayout()
        self._7.setObjectName("_7")
        spacerItem12 = QtGui.QSpacerItem(16, 16, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._7.addItem(spacerItem12, 1, 0, 1, 1)
        self.textLabel1_9 = QtGui.QLabel(self.tab_2)
        self.textLabel1_9.setAlignment(QtCore.Qt.AlignVCenter)
        self.textLabel1_9.setWordWrap(False)
        self.textLabel1_9.setObjectName("textLabel1_9")
        self._7.addWidget(self.textLabel1_9, 0, 0, 1, 2)
        self.validateBox = QtGui.QComboBox(self.tab_2)
        self.validateBox.setObjectName("validateBox")
        self.validateBox.addItem("")
        self.validateBox.addItem("")
        self.validateBox.addItem("")
        self.validateBox.addItem("")
        self._7.addWidget(self.validateBox, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self._7, 2, 1, 1, 2)
        spacerItem13 = QtGui.QSpacerItem(21, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem13, 3, 1, 1, 1)
        self._2 = QtGui.QGridLayout()
        self._2.setObjectName("_2")
        self.textLabel3 = QtGui.QLabel(self.tab_2)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self._2.addWidget(self.textLabel3, 3, 1, 1, 1)
        self.certKeyFileButton = QtGui.QToolButton(self.tab_2)
        self.certKeyFileButton.setEnabled(False)
        self.certKeyFileButton.setObjectName("certKeyFileButton")
        self._2.addWidget(self.certKeyFileButton, 3, 3, 1, 1)
        self.certFileButton = QtGui.QToolButton(self.tab_2)
        self.certFileButton.setEnabled(False)
        self.certFileButton.setObjectName("certFileButton")
        self._2.addWidget(self.certFileButton, 2, 3, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(16, 16, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem14, 1, 0, 1, 1)
        self.certFileEdit = QtGui.QLineEdit(self.tab_2)
        self.certFileEdit.setEnabled(False)
        self.certFileEdit.setObjectName("certFileEdit")
        self._2.addWidget(self.certFileEdit, 2, 2, 1, 1)
        self.useClientCertBox = QtGui.QCheckBox(self.tab_2)
        self.useClientCertBox.setEnabled(False)
        self.useClientCertBox.setObjectName("useClientCertBox")
        self._2.addWidget(self.useClientCertBox, 1, 1, 1, 3)
        self.certKeyfileEdit = QtGui.QLineEdit(self.tab_2)
        self.certKeyfileEdit.setEnabled(False)
        self.certKeyfileEdit.setObjectName("certKeyfileEdit")
        self._2.addWidget(self.certKeyfileEdit, 3, 2, 1, 1)
        self.textLabel2_2 = QtGui.QLabel(self.tab_2)
        self.textLabel2_2.setWordWrap(False)
        self.textLabel2_2.setObjectName("textLabel2_2")
        self._2.addWidget(self.textLabel2_2, 2, 1, 1, 1)
        self.textLabel1_3 = QtGui.QLabel(self.tab_2)
        self.textLabel1_3.setWordWrap(False)
        self.textLabel1_3.setObjectName("textLabel1_3")
        self._2.addWidget(self.textLabel1_3, 0, 0, 1, 4)
        self.gridLayout_4.addLayout(self._2, 4, 1, 1, 2)
        spacerItem15 = QtGui.QSpacerItem(175, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem15, 5, 2, 1, 1)
        self.serverWidget.addTab(self.tab_2, "")
        self.vboxlayout.addWidget(self.splitter2)
        self.line1 = QtGui.QFrame(ServerDialogDesign)
        self.line1.setFrameShape(QtGui.QFrame.HLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.vboxlayout.addWidget(self.line1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem16 = QtGui.QSpacerItem(383, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem16)
        self.okButton = QtGui.QPushButton(ServerDialogDesign)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.applyButton = QtGui.QPushButton(ServerDialogDesign)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyButton.sizePolicy().hasHeightForWidth())
        self.applyButton.setSizePolicy(sizePolicy)
        self.applyButton.setObjectName("applyButton")
        self.hboxlayout.addWidget(self.applyButton)
        self.cancelButton = QtGui.QPushButton(ServerDialogDesign)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(ServerDialogDesign)
        self.serverWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.applyButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.saveServer)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.reject)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.saveCloseDialog)
        QtCore.QObject.connect(self.addButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.addServer)
        QtCore.QObject.connect(self.deleteButton, QtCore.SIGNAL("clicked()"), ServerDialogDesign.deleteServer)
        QtCore.QObject.connect(self.addBaseDN, QtCore.SIGNAL("clicked()"), ServerDialogDesign.addBaseDn)
        QtCore.QMetaObject.connectSlotsByName(ServerDialogDesign)
        ServerDialogDesign.setTabOrder(self.addButton, self.deleteButton)
        ServerDialogDesign.setTabOrder(self.deleteButton, self.serverWidget)
        ServerDialogDesign.setTabOrder(self.serverWidget, self.hostLineEdit)
        ServerDialogDesign.setTabOrder(self.hostLineEdit, self.portSpinBox)
        ServerDialogDesign.setTabOrder(self.portSpinBox, self.aliasBox)
        ServerDialogDesign.setTabOrder(self.aliasBox, self.baseBox)
        ServerDialogDesign.setTabOrder(self.baseBox, self.bindAnonBox)
        ServerDialogDesign.setTabOrder(self.bindAnonBox, self.methodBox)
        ServerDialogDesign.setTabOrder(self.methodBox, self.bindLineEdit)
        ServerDialogDesign.setTabOrder(self.bindLineEdit, self.passwordLineEdit)
        ServerDialogDesign.setTabOrder(self.passwordLineEdit, self.okButton)
        ServerDialogDesign.setTabOrder(self.okButton, self.applyButton)
        ServerDialogDesign.setTabOrder(self.applyButton, self.cancelButton)

    def retranslateUi(self, ServerDialogDesign):
        ServerDialogDesign.setWindowTitle(QtGui.QApplication.translate("ServerDialogDesign", "Manage Server List", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "&Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setShortcut(QtGui.QApplication.translate("ServerDialogDesign", "Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setShortcut(QtGui.QApplication.translate("ServerDialogDesign", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))
        self.networkLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "NO", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("ServerDialogDesign", "<b>Network options</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel9.setText(QtGui.QApplication.translate("ServerDialogDesign", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel8.setText(QtGui.QApplication.translate("ServerDialogDesign", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasBox.setText(QtGui.QApplication.translate("ServerDialogDesign", "Follow aliases", None, QtGui.QApplication.UnicodeUTF8))
        self.baseBox.setText(QtGui.QApplication.translate("ServerDialogDesign", "Use Base DNs provided by the server", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("ServerDialogDesign", "<b>LDAP options</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.removeBaseDN.setText(QtGui.QApplication.translate("ServerDialogDesign", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.addBaseDN.setText(QtGui.QApplication.translate("ServerDialogDesign", "Add Base DN", None, QtGui.QApplication.UnicodeUTF8))
        self.serverWidget.setTabText(self.serverWidget.indexOf(self.tab), QtGui.QApplication.translate("ServerDialogDesign", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("ServerDialogDesign", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Bind options</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.bindAnonBox.setText(QtGui.QApplication.translate("ServerDialogDesign", "Anonymous bind", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("ServerDialogDesign", "Mechanism:", None, QtGui.QApplication.UnicodeUTF8))
        self.methodBox.setItemText(0, QtGui.QApplication.translate("ServerDialogDesign", "Simple", None, QtGui.QApplication.UnicodeUTF8))
        self.methodBox.setItemText(1, QtGui.QApplication.translate("ServerDialogDesign", "SASL CRAM-MD5", None, QtGui.QApplication.UnicodeUTF8))
        self.methodBox.setItemText(2, QtGui.QApplication.translate("ServerDialogDesign", "SASL DIGEST-MD5", None, QtGui.QApplication.UnicodeUTF8))
        self.methodBox.setItemText(3, QtGui.QApplication.translate("ServerDialogDesign", "SASL EXTERNAL", None, QtGui.QApplication.UnicodeUTF8))
        self.methodBox.setItemText(4, QtGui.QApplication.translate("ServerDialogDesign", "SASL GSSAPI", None, QtGui.QApplication.UnicodeUTF8))
        self.methodBox.setItemText(5, QtGui.QApplication.translate("ServerDialogDesign", "SASL Login", None, QtGui.QApplication.UnicodeUTF8))
        self.methodBox.setItemText(6, QtGui.QApplication.translate("ServerDialogDesign", "SASL Plain", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel10.setText(QtGui.QApplication.translate("ServerDialogDesign", "Bind as:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel12.setText(QtGui.QApplication.translate("ServerDialogDesign", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.authLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "SO", None, QtGui.QApplication.UnicodeUTF8))
        self.serverWidget.setTabText(self.serverWidget.indexOf(self.tab1), QtGui.QApplication.translate("ServerDialogDesign", "Authentification", None, QtGui.QApplication.UnicodeUTF8))
        self.securityLabel.setText(QtGui.QApplication.translate("ServerDialogDesign", "SO", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_10.setText(QtGui.QApplication.translate("ServerDialogDesign", "<b>Security options</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.encryptionBox.setItemText(0, QtGui.QApplication.translate("ServerDialogDesign", "Unencrypted connection", None, QtGui.QApplication.UnicodeUTF8))
        self.encryptionBox.setItemText(1, QtGui.QApplication.translate("ServerDialogDesign", "Transport Layer Security (TLS)", None, QtGui.QApplication.UnicodeUTF8))
        self.encryptionBox.setItemText(2, QtGui.QApplication.translate("ServerDialogDesign", "Secure Socket Layer (SSL)", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_9.setText(QtGui.QApplication.translate("ServerDialogDesign", "<b>Validate server certificate</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.validateBox.setItemText(0, QtGui.QApplication.translate("ServerDialogDesign", "Never", None, QtGui.QApplication.UnicodeUTF8))
        self.validateBox.setItemText(1, QtGui.QApplication.translate("ServerDialogDesign", "Allow", None, QtGui.QApplication.UnicodeUTF8))
        self.validateBox.setItemText(2, QtGui.QApplication.translate("ServerDialogDesign", "Try", None, QtGui.QApplication.UnicodeUTF8))
        self.validateBox.setItemText(3, QtGui.QApplication.translate("ServerDialogDesign", "Demand", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("ServerDialogDesign", "Certificate keyfile:", None, QtGui.QApplication.UnicodeUTF8))
        self.certKeyFileButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.certFileButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.useClientCertBox.setText(QtGui.QApplication.translate("ServerDialogDesign", "Use client certificates", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_2.setText(QtGui.QApplication.translate("ServerDialogDesign", "Certificate file:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3.setText(QtGui.QApplication.translate("ServerDialogDesign", "<b>Client certificate options</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.serverWidget.setTabText(self.serverWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ServerDialogDesign", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("ServerDialogDesign", "Alt+O", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setShortcut(QtGui.QApplication.translate("ServerDialogDesign", "Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("ServerDialogDesign", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setShortcut(QtGui.QApplication.translate("ServerDialogDesign", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))

