# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/debris/devel/git/luma/resources/forms/plugins/search/FilterWizardDesign.ui'
#
# Created: Tue Mar 29 15:43:04 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FilterWizard(object):
    def filterTypeBoxf, FilterWizard):
        FilterWizard.setObjectName("FilterWizard")
        FilterWizard.resize(377, 305)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FilterWizard.sizePolicy().hasHeightForWidth())
        FilterWizard.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(FilterWizard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.criteriaGroup = QtGui.QGroupBox(FilterWizard)
        self.criteriaGroup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.criteriaGroup.setObjectName("criteriaGroup")
        self.gridLayout_2 = QtGui.QGridLayout(self.criteriaGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbObjectClass = QtGui.QRadioButton(self.criteriaGroup)
        self.rbObjectClass.setChecked(True)
        self.rbObjectClass.setObjectName("rbObjectClass")
        self.gridLayout_2.addWidget(self.rbObjectClass, 0, 0, 1, 1)
        self.filterTypeBox = QtGui.QComboBox(self.criteriaGroup)
        self.filterTypeBox.setEnabled(False)
        self.filterTypeBox.setObjectName("filterTypeBox")
        self.gridLayout_2.addWidget(self.filterTypeBox, 1, 3, 1, 3)
        self.criteriaEdit = QtGui.QLineEdit(self.criteriaGroup)
        self.criteriaEdit.setEnabled(False)
        self.criteriaEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.criteriaEdit.setObjectName("criteriaEdit")
        self.gridLayout_2.addWidget(self.criteriaEdit, 3, 0, 1, 5)
        self.rbAttribute = QtGui.QRadioButton(self.criteriaGroup)
        self.rbAttribute.setObjectName("rbAttribute")
        self.gridLayout_2.addWidget(self.rbAttribute, 0, 1, 1, 5)
        self.insertButton = QtGui.QPushButton(self.criteriaGroup)
        self.insertButton.setObjectName("insertButton")
        self.gridLayout_2.addWidget(self.insertButton, 3, 5, 1, 1)
        self.optionBox = QtGui.QComboBox(self.criteriaGroup)
        self.optionBox.setObjectName("optionBox")
        self.gridLayout_2.addWidget(self.optionBox, 1, 0, 1, 3)
        self.verticalLayout.addWidget(self.criteriaGroup)
        self.line_2 = QtGui.QFrame(FilterWizard)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.undoButton = QtGui.QToolButton(FilterWizard)
        self.undoButton.setEnabled(False)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_2.addWidget(self.undoButton)
        self.redoButton = QtGui.QToolButton(FilterWizard)
        self.redoButton.setEnabled(False)
        self.redoButton.setObjectName("redoButton")
        self.horizontalLayout_2.addWidget(self.redoButton)
        self.vline1 = QtGui.QFrame(FilterWizard)
        self.vline1.setFrameShape(QtGui.QFrame.VLine)
        self.vline1.setFrameShadow(QtGui.QFrame.Sunken)
        self.vline1.setObjectName("vline1")
        self.horizontalLayout_2.addWidget(self.vline1)
        self.notButton = QtGui.QToolButton(FilterWizard)
        self.notButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notButton.sizePolicy().hasHeightForWidth())
        self.notButton.setSizePolicy(sizePolicy)
        self.notButton.setObjectName("notButton")
        self.horizontalLayout_2.addWidget(self.notButton)
        self.andButton = QtGui.QToolButton(FilterWizard)
        self.andButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.andButton.sizePolicy().hasHeightForWidth())
        self.andButton.setSizePolicy(sizePolicy)
        self.andButton.setCheckable(False)
        self.andButton.setObjectName("andButton")
        self.horizontalLayout_2.addWidget(self.andButton)
        self.orButton = QtGui.QToolButton(FilterWizard)
        self.orButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orButton.sizePolicy().hasHeightForWidth())
        self.orButton.setSizePolicy(sizePolicy)
        self.orButton.setCheckable(False)
        self.orButton.setObjectName("orButton")
        self.horizontalLayout_2.addWidget(self.orButton)
        self.vline2 = QtGui.QFrame(FilterWizard)
        self.vline2.setFrameShape(QtGui.QFrame.VLine)
        self.vline2.setFrameShadow(QtGui.QFrame.Sunken)
        self.vline2.setObjectName("vline2")
        self.horizontalLayout_2.addWidget(self.vline2)
        self.specialCharBox = QtGui.QComboBox(FilterWizard)
        self.specialCharBox.setObjectName("specialCharBox")
        self.horizontalLayout_2.addWidget(self.specialCharBox)
        self.addSpecialCharButton = QtGui.QToolButton(FilterWizard)
        self.addSpecialCharButton.setObjectName("addSpecialCharButton")
        self.horizontalLayout_2.addWidget(self.addSpecialCharButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.filterEdit = QtGui.QPlainTextEdit(FilterWizard)
        self.filterEdit.setTabChangesFocus(True)
        self.filterEdit.setObjectName("filterEdit")
        self.verticalLayout.addWidget(self.filterEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.saveButton = QtGui.QPushButton(FilterWizard)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.clearButton = QtGui.QPushButton(FilterWizard)
        self.clearButton.setEnabled(False)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FilterWizard)
        QtCore.QMetaObject.connectSlotsByName(FilterWizard)
        FilterWizard.setTabOrder(self.rbObjectClass, self.rbAttribute)
        FilterWizard.setTabOrder(self.rbAttribute, self.optionBox)
        FilterWizard.setTabOrder(self.optionBox, self.filterTypeBox)
        FilterWizard.setTabOrder(self.filterTypeBox, self.criteriaEdit)
        FilterWizard.setTabOrder(self.criteriaEdit, self.insertButton)
        FilterWizard.setTabOrder(self.insertButton, self.filterEdit)
        FilterWizard.setTabOrder(self.filterEdit, self.saveButton)
        FilterWizard.setTabOrder(self.saveButton, self.clearButton)
        FilterWizard.setTabOrder(self.clearButton, self.undoButton)
        FilterWizard.setTabOrder(self.undoButton, self.redoButton)
        FilterWizard.setTabOrder(self.redoButton, self.notButton)
        FilterWizard.setTabOrder(self.notButton, self.andButton)
        FilterWizard.setTabOrder(self.andButton, self.orButton)
        FilterWizard.setTabOrder(self.orButton, self.specialCharBox)
        FilterWizard.setTabOrder(self.specialCharBox, self.addSpecialCharButton)

    def retranslateUi(self, FilterWizard):
        FilterWizard.setWindowTitle(QtGui.QApplication.translate("FilterWizard", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.criteriaGroup.setTitle(QtGui.QApplication.translate("FilterWizard", "Filter criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.rbObjectClass.setText(QtGui.QApplication.translate("FilterWizard", "ObjectClass", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAttribute.setText(QtGui.QApplication.translate("FilterWizard", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.insertButton.setToolTip(QtGui.QApplication.translate("FilterWizard", "Click to insert the search criteria in the filter below.", None, QtGui.QApplication.UnicodeUTF8))
        self.insertButton.setText(QtGui.QApplication.translate("FilterWizard", "&Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setText(QtGui.QApplication.translate("FilterWizard", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setText(QtGui.QApplication.translate("FilterWizard", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.notButton.setToolTip(QtGui.QApplication.translate("FilterWizard", "Click to negate selection", None, QtGui.QApplication.UnicodeUTF8))
        self.notButton.setText(QtGui.QApplication.translate("FilterWizard", "not", None, QtGui.QApplication.UnicodeUTF8))
        self.andButton.setToolTip(QtGui.QApplication.translate("FilterWizard", "Click to \'and\' selection", None, QtGui.QApplication.UnicodeUTF8))
        self.andButton.setText(QtGui.QApplication.translate("FilterWizard", "and", None, QtGui.QApplication.UnicodeUTF8))
        self.orButton.setToolTip(QtGui.QApplication.translate("FilterWizard", "Click to \'or\' selection", None, QtGui.QApplication.UnicodeUTF8))
        self.orButton.setText(QtGui.QApplication.translate("FilterWizard", "or", None, QtGui.QApplication.UnicodeUTF8))
        self.specialCharBox.setToolTip(QtGui.QApplication.translate("FilterWizard", "Select special character to add", None, QtGui.QApplication.UnicodeUTF8))
        self.addSpecialCharButton.setToolTip(QtGui.QApplication.translate("FilterWizard", "Add escaped special character", None, QtGui.QApplication.UnicodeUTF8))
        self.addSpecialCharButton.setText(QtGui.QApplication.translate("FilterWizard", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("FilterWizard", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("FilterWizard", "&Clear", None, QtGui.QApplication.UnicodeUTF8))

