# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/debris/devel/git/luma/resources/forms/plugins/search/SearchFormDesign.ui'
#
# Created: Mon Mar 28 04:50:55 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SearchForm(object):
    def setupUi(self, SearchForm):
        SearchForm.setObjectName("SearchForm")
        SearchForm.resize(377, 253)
        self.verticalLayout = QtGui.QVBoxLayout(SearchForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.optionsGrid = QtGui.QGroupBox(SearchForm)
        self.optionsGrid.setObjectName("optionsGrid")
        self.gridLayout_2 = QtGui.QGridLayout(self.optionsGrid)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.serverLabel = QtGui.QLabel(self.optionsGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverLabel.sizePolicy().hasHeightForWidth())
        self.serverLabel.setSizePolicy(sizePolicy)
        self.serverLabel.setObjectName("serverLabel")
        self.gridLayout_2.addWidget(self.serverLabel, 2, 0, 1, 1)
        self.baseDNLabel = QtGui.QLabel(self.optionsGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseDNLabel.sizePolicy().hasHeightForWidth())
        self.baseDNLabel.setSizePolicy(sizePolicy)
        self.baseDNLabel.setObjectName("baseDNLabel")
        self.gridLayout_2.addWidget(self.baseDNLabel, 3, 0, 1, 1)
        self.filterLabel = QtGui.QLabel(self.optionsGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterLabel.sizePolicy().hasHeightForWidth())
        self.filterLabel.setSizePolicy(sizePolicy)
        self.filterLabel.setObjectName("filterLabel")
        self.gridLayout_2.addWidget(self.filterLabel, 4, 0, 1, 1)
        self.baseDNBox = QtGui.QComboBox(self.optionsGrid)
        self.baseDNBox.setEnabled(True)
        self.baseDNBox.setObjectName("baseDNBox")
        self.gridLayout_2.addWidget(self.baseDNBox, 3, 1, 1, 2)
        self.serverBox = QtGui.QComboBox(self.optionsGrid)
        self.serverBox.setEnabled(True)
        self.serverBox.setObjectName("serverBox")
        self.gridLayout_2.addWidget(self.serverBox, 2, 1, 1, 2)
        self.filterBox = QtGui.QComboBox(self.optionsGrid)
        self.filterBox.setEnabled(False)
        self.filterBox.setObjectName("filterBox")
        self.gridLayout_2.addWidget(self.filterBox, 4, 1, 1, 1)
        self.filterWizardToolButton = QtGui.QToolButton(self.optionsGrid)
        self.filterWizardToolButton.setEnabled(True)
        self.filterWizardToolButton.setObjectName("filterWizardToolButton")
        self.gridLayout_2.addWidget(self.filterWizardToolButton, 4, 2, 1, 1)
        self.scopeBox = QtGui.QComboBox(self.optionsGrid)
        self.scopeBox.setMaxVisibleItems(3)
        self.scopeBox.setMaxCount(3)
        self.scopeBox.setDuplicatesEnabled(True)
        self.scopeBox.setObjectName("scopeBox")
        self.gridLayout_2.addWidget(self.scopeBox, 5, 1, 1, 2)
        self.sizeLimitSpinBox = QtGui.QSpinBox(self.optionsGrid)
        self.sizeLimitSpinBox.setObjectName("sizeLimitSpinBox")
        self.gridLayout_2.addWidget(self.sizeLimitSpinBox, 6, 1, 1, 2)
        self.sizeLimitLabel = QtGui.QLabel(self.optionsGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeLimitLabel.sizePolicy().hasHeightForWidth())
        self.sizeLimitLabel.setSizePolicy(sizePolicy)
        self.sizeLimitLabel.setObjectName("sizeLimitLabel")
        self.gridLayout_2.addWidget(self.sizeLimitLabel, 6, 0, 1, 1)
        self.label = QtGui.QLabel(self.optionsGrid)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.optionsGrid)
        self.line = QtGui.QFrame(SearchForm)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.searchHLayout = QtGui.QHBoxLayout()
        self.searchHLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.searchHLayout.setObjectName("searchHLayout")
        self.searchEdit = QtGui.QLineEdit(SearchForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchEdit.sizePolicy().hasHeightForWidth())
        self.searchEdit.setSizePolicy(sizePolicy)
        self.searchEdit.setObjectName("searchEdit")
        self.searchHLayout.addWidget(self.searchEdit)
        self.searchButton = QtGui.QPushButton(SearchForm)
        self.searchButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName("searchButton")
        self.searchHLayout.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.searchHLayout)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(SearchForm)
        self.scopeBox.setCurrentIndex(-1)
        QtCore.QObject.connect(self.searchEdit, QtCore.SIGNAL("returnPressed()"), self.searchButton.click)
        QtCore.QMetaObject.connectSlotsByName(SearchForm)

    def retranslateUi(self, SearchForm):
        SearchForm.setWindowTitle(QtGui.QApplication.translate("SearchForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsGrid.setTitle(QtGui.QApplication.translate("SearchForm", "Search options", None, QtGui.QApplication.UnicodeUTF8))
        self.serverLabel.setText(QtGui.QApplication.translate("SearchForm", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.baseDNLabel.setText(QtGui.QApplication.translate("SearchForm", "Base DN:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterLabel.setText(QtGui.QApplication.translate("SearchForm", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterWizardToolButton.setToolTip(QtGui.QApplication.translate("SearchForm", "Open the Filter Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.filterWizardToolButton.setText(QtGui.QApplication.translate("SearchForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeLimitLabel.setToolTip(QtGui.QApplication.translate("SearchForm", "Limit the number of entries to retrive. (0 = None)", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeLimitLabel.setText(QtGui.QApplication.translate("SearchForm", "Size limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SearchForm", "Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("SearchForm", "Search", None, QtGui.QApplication.UnicodeUTF8))

