# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/debris/devel/git/luma/resources/forms/plugins/search/SearchPluginDesign.ui'
#
# Created: Wed Mar 23 03:36:57 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SearchPlugin(object):
    def setupUi(self, SearchPlugin):
        SearchPlugin.setObjectName("SearchPlugin")
        SearchPlugin.resize(717, 422)
        self.gridLayout_4 = QtGui.QGridLayout(SearchPlugin)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rightGrid = QtGui.QGridLayout()
        self.rightGrid.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.rightGrid.setObjectName("rightGrid")
        self.searchHLayout = QtGui.QHBoxLayout()
        self.searchHLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.searchHLayout.setObjectName("searchHLayout")
        self.searchEdit = QtGui.QLineEdit(SearchPlugin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchEdit.sizePolicy().hasHeightForWidth())
        self.searchEdit.setSizePolicy(sizePolicy)
        self.searchEdit.setObjectName("searchEdit")
        self.searchHLayout.addWidget(self.searchEdit)
        self.searchButton = QtGui.QPushButton(SearchPlugin)
        self.searchButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName("searchButton")
        self.searchHLayout.addWidget(self.searchButton)
        self.rightGrid.addLayout(self.searchHLayout, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(SearchPlugin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(350, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidget = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 348, 365))
        self.scrollAreaWidget.setObjectName("scrollAreaWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.optionsGrid = QtGui.QGroupBox(self.scrollAreaWidget)
        self.optionsGrid.setObjectName("optionsGrid")
        self.gridLayout_2 = QtGui.QGridLayout(self.optionsGrid)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.serverLabel = QtGui.QLabel(self.optionsGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverLabel.sizePolicy().hasHeightForWidth())
        self.serverLabel.setSizePolicy(sizePolicy)
        self.serverLabel.setObjectName("serverLabel")
        self.gridLayout_2.addWidget(self.serverLabel, 2, 0, 1, 1)
        self.baseDNLabel = QtGui.QLabel(self.optionsGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseDNLabel.sizePolicy().hasHeightForWidth())
        self.baseDNLabel.setSizePolicy(sizePolicy)
        self.baseDNLabel.setObjectName("baseDNLabel")
        self.gridLayout_2.addWidget(self.baseDNLabel, 3, 0, 1, 1)
        self.filterLabel = QtGui.QLabel(self.optionsGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterLabel.sizePolicy().hasHeightForWidth())
        self.filterLabel.setSizePolicy(sizePolicy)
        self.filterLabel.setObjectName("filterLabel")
        self.gridLayout_2.addWidget(self.filterLabel, 4, 0, 1, 1)
        self.baseDNBox = QtGui.QComboBox(self.optionsGrid)
        self.baseDNBox.setEnabled(True)
        self.baseDNBox.setObjectName("baseDNBox")
        self.gridLayout_2.addWidget(self.baseDNBox, 3, 1, 1, 2)
        self.serverBox = QtGui.QComboBox(self.optionsGrid)
        self.serverBox.setEnabled(True)
        self.serverBox.setObjectName("serverBox")
        self.gridLayout_2.addWidget(self.serverBox, 2, 1, 1, 2)
        self.filterBox = QtGui.QComboBox(self.optionsGrid)
        self.filterBox.setEnabled(False)
        self.filterBox.setObjectName("filterBox")
        self.gridLayout_2.addWidget(self.filterBox, 4, 1, 1, 1)
        self.filterWizardToolButton = QtGui.QToolButton(self.optionsGrid)
        self.filterWizardToolButton.setEnabled(False)
        self.filterWizardToolButton.setObjectName("filterWizardToolButton")
        self.gridLayout_2.addWidget(self.filterWizardToolButton, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.optionsGrid)
        self.searchLevelGroup = QtGui.QGroupBox(self.scrollAreaWidget)
        self.searchLevelGroup.setObjectName("searchLevelGroup")
        self.gridLayout = QtGui.QGridLayout(self.searchLevelGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.scopeBox = QtGui.QComboBox(self.searchLevelGroup)
        self.scopeBox.setMaxVisibleItems(3)
        self.scopeBox.setMaxCount(3)
        self.scopeBox.setDuplicatesEnabled(True)
        self.scopeBox.setObjectName("scopeBox")
        self.scopeBox.addItem("")
        self.scopeBox.addItem("")
        self.scopeBox.addItem("")
        self.gridLayout.addWidget(self.scopeBox, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.searchLevelGroup)
        self.seacrhConstraintsGroup = QtGui.QGroupBox(self.scrollAreaWidget)
        self.seacrhConstraintsGroup.setObjectName("seacrhConstraintsGroup")
        self.gridLayout_3 = QtGui.QGridLayout(self.seacrhConstraintsGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.aliasBox = QtGui.QCheckBox(self.seacrhConstraintsGroup)
        self.aliasBox.setObjectName("aliasBox")
        self.gridLayout_3.addWidget(self.aliasBox, 0, 0, 1, 2)
        self.sizeLimitLabel = QtGui.QLabel(self.seacrhConstraintsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeLimitLabel.sizePolicy().hasHeightForWidth())
        self.sizeLimitLabel.setSizePolicy(sizePolicy)
        self.sizeLimitLabel.setObjectName("sizeLimitLabel")
        self.gridLayout_3.addWidget(self.sizeLimitLabel, 1, 0, 1, 1)
        self.sizeLimitSpinBox = QtGui.QSpinBox(self.seacrhConstraintsGroup)
        self.sizeLimitSpinBox.setObjectName("sizeLimitSpinBox")
        self.gridLayout_3.addWidget(self.sizeLimitSpinBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.seacrhConstraintsGroup)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidget)
        self.rightGrid.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.rightGrid, 0, 0, 1, 1)
        self.searchResultWidget = QtGui.QTabWidget(SearchPlugin)
        self.searchResultWidget.setObjectName("searchResultWidget")
        self.gridLayout_4.addWidget(self.searchResultWidget, 0, 1, 1, 1)

        self.retranslateUi(SearchPlugin)
        self.scopeBox.setCurrentIndex(2)
        QtCore.QObject.connect(self.searchButton, QtCore.SIGNAL("clicked()"), SearchPlugin.search)
        QtCore.QObject.connect(self.filterWizardToolButton, QtCore.SIGNAL("clicked()"), SearchPlugin.showFilterWizard)
        QtCore.QObject.connect(self.searchEdit, QtCore.SIGNAL("returnPressed()"), self.searchButton.click)
        QtCore.QObject.connect(self.serverBox, QtCore.SIGNAL("currentIndexChanged(int)"), SearchPlugin.serverChanged)
        QtCore.QMetaObject.connectSlotsByName(SearchPlugin)
        SearchPlugin.setTabOrder(self.searchEdit, self.searchButton)
        SearchPlugin.setTabOrder(self.searchButton, self.serverBox)
        SearchPlugin.setTabOrder(self.serverBox, self.baseDNBox)
        SearchPlugin.setTabOrder(self.baseDNBox, self.filterBox)
        SearchPlugin.setTabOrder(self.filterBox, self.filterWizardToolButton)
        SearchPlugin.setTabOrder(self.filterWizardToolButton, self.searchResultWidget)

    def retranslateUi(self, SearchPlugin):
        SearchPlugin.setWindowTitle(QtGui.QApplication.translate("SearchPlugin", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("SearchPlugin", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsGrid.setTitle(QtGui.QApplication.translate("SearchPlugin", "Server options", None, QtGui.QApplication.UnicodeUTF8))
        self.serverLabel.setText(QtGui.QApplication.translate("SearchPlugin", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.baseDNLabel.setText(QtGui.QApplication.translate("SearchPlugin", "Base DN:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterLabel.setText(QtGui.QApplication.translate("SearchPlugin", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterWizardToolButton.setToolTip(QtGui.QApplication.translate("SearchPlugin", "Open the Filter Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.filterWizardToolButton.setText(QtGui.QApplication.translate("SearchPlugin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.searchLevelGroup.setTitle(QtGui.QApplication.translate("SearchPlugin", "Search level", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeBox.setItemText(0, QtGui.QApplication.translate("SearchPlugin", "SCOPE_BASE", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeBox.setItemText(1, QtGui.QApplication.translate("SearchPlugin", "SCOPE_ONELEVEL", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeBox.setItemText(2, QtGui.QApplication.translate("SearchPlugin", "SCOPE_SUBTREE", None, QtGui.QApplication.UnicodeUTF8))
        self.seacrhConstraintsGroup.setTitle(QtGui.QApplication.translate("SearchPlugin", "Search constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasBox.setText(QtGui.QApplication.translate("SearchPlugin", "Follow aliases", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeLimitLabel.setToolTip(QtGui.QApplication.translate("SearchPlugin", "Limit the number of entries to retrive. (0 = None)", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeLimitLabel.setText(QtGui.QApplication.translate("SearchPlugin", "Size limit:", None, QtGui.QApplication.UnicodeUTF8))

